### ISSUE TITLE
[Update] New PodcastGenerator v3.0

### ISSUE THREAD

**Issue by RicardoVelaC** [chambana-net/docker-podcastgen#2]
Have you plans to update the container to new version of PG?

[PodcastGenerator v3.0](https://github.com/albertobeta/PodcastGenerator/releases/tag/v3.0)

**Comment by jheretic** [comment]
Hi @RicardoVelaC, I've been a little swamped with work lately to keep up with this, but thanks for letting me know about v3.0. I'd be happy to update it to 3.0 when I get a chance, assuming it isn't a huge amount of work.

**Comment by cvengler** [comment]
Also PG 3.0.1 came out last week.
I just looked a bit at the run.sh script and found that it is still using the old sourceforge URL.

We switched to GitHub in 2015 I believe.
Here is a link to the new release page: https://github.com/albertobeta/PodcastGenerator/releases

Also thanks for maintaining this script

**Comment by nemosmithasf** [comment]
Looking forward to this
